apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    namespace: default
    server: https://103.74.253.14:6443
  source:
    path: manifest
    repoURL: https://github.com/Berubell9/argoCD_deploy_nginx.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      enabled: true